# User's settings - can change there defaults, or
# change them for a while using hotkeys.

user_settings: {
  'show_hidden_files': False, # show files starts with "."
  'show_hints': False         # starts app with hotkeys list
}

# Global variables needed for app properly working.
# Don't change them if you don't understand a code!

global_variables: {
  'highlighted_item': 0,
  'path': "",
  'key': 71,
  'new_name': "",
  'naming': [False, "nothing"],
  'last_path': "",
  'copy_path': "",
  'current_page': 1,
  'items_pages': 1,
  'delete_warning': False,
  'preview_file': False,
  'preview_len': 0,
  'preview_line': 0
}